# Generated by Django 4.2.1 on 2023-05-17 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Membershipapi', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_product', models.CharField(max_length=100)),
                ('order_amount', models.CharField(max_length=25)),
                ('order_payment_id', models.CharField(max_length=100)),
                ('isPaid', models.BooleanField(default=False)),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('user_email', models.CharField(default='null', max_length=150)),
                ('product_name', models.CharField(default='null', max_length=1530)),
                ('order_dateTele', models.CharField(default='2023-05-17', max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='TransationIdone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id1', models.CharField(max_length=2322)),
                ('dateid', models.CharField(max_length=232)),
                ('message', models.CharField(max_length=232)),
                ('ProductData', models.CharField(max_length=43343333, null=True)),
                ('date_created', models.CharField(default='2023-05-17', max_length=550)),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_token_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('plan', models.CharField(blank=True, max_length=100, null=True)),
                ('paymentStatus', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('tranid', models.CharField(blank=True, max_length=100, null=True)),
                ('order_payment_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('phoneNumber', models.CharField(max_length=100, null=True)),
                ('ordrDate', models.CharField(default='2023-05-17', max_length=155)),
                ('courseSelected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Membershipapi.plan')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
        ),
    ]
